/**
 *
 * 4 - Must have
 * 3 - Lower priority but still good
 * 2 - Needed for folks with missing IotMs
 * 1 - Nice-to-have
 * 0 - Unranked
 */

export const ranking: Record<string, number> = {
  "ninja snowman assassin": 4,
  "white lion": 4,
  whitesnake: 4,
  "mountain man": 4,
  "Black Crayon Frat Orc": 4,
  "swarm of ghuol whelps": 4,
  "big swarm of ghuol whelps": 4,
  "giant swarm of ghuol whelps": 4,
  "modern zmobie": 4,
  "dirty old lihc": 4,
  "Green Ops Soldier": 4,
  Skinflute: 4,
  "Camel's Toe": 4,
  Astronomer: 4,
  "forest spirit": 4,
  beanbat: 4,
  blur: 4,
  "Baa'baa'bu'ran": 4,
  "red butler": 3,
  "Witchess Knight": 3,
  "Witchess Bishop": 3,
  "Witchess Queen": 3,
  "Witchess King": 3,
  "Witchess Witch": 3,
  "sausage goblin": 3,
  "Black Crayon Man": 3,
  "Black Crayon Beast": 3,
  "Black Crayon Golem": 3,
  "Black Crayon Undead Thing": 3,
  "Black Crayon Manloid": 3,
  "Black Crayon Beetle": 3,
  "Black Crayon Hippy": 3,
  "Black Crayon Demon": 3,
  "Black Crayon Shambling Monstrosity": 3,
  "Black Crayon Fish": 3,
  "Black Crayon Goblin": 3,
  "Black Crayon Pirate": 3,
  "Black Crayon Flower": 3,
  "Black Crayon Spiraling Shape": 3,
  "Black Crayon Crimbo Elf": 3,
  "Black Crayon Mer-kin": 3,
  "Black Crayon Slime": 3,
  "Black Crayon Penguin": 3,
  "Black Crayon Elemental": 3,
  "Black Crayon Constellation": 3,
  "Black Crayon Hobo": 3,
  "oil cartel": 3,
  "Racecar Bob": 3,
  "Bob Racecar": 3,
  "Knight in White Satin": 3,
  "pygmy witch accountant": 3,
  "pygmy janitor": 3,
  "erudite gremlin (tool)": 3,
  "batwinged gremlin (tool)": 3,
  "vegetable gremlin (tool)": 3,
  "spider gremlin (tool)": 3,
  "War Frat Mobile Grill Unit": 2,
  lobsterfrogman: 2,
  "fantasy bandit": 2,
  screambat: 2,
  "Knob Goblin Harem Girl": 1,
  "dairy goat": 1,
  "lynyrd skinner": 1,
  "Bram the Stoker": 1,
  "pygmy bowler": 1,
  "dense liana": 1,
  "eye in the darkness": 1,
  "slithering thing": 1,
};
